services:
  homelab:
    container_name: homelab
    restart: unless-stopped  
    build:
      context: "."
      dockerfile: "Dockerfile"
    user: "1000:1000"
    environment:
      HOME: /tmp
      XDG_CONFIG_HOME: /tmp/.config
    volumes: 
      - ".:/var/www/html"
      # - "/var/www/html/vendor"       # Protects vendor created by Dockerfile
      # - "/var/www/html/node_modules" # Protects node_modules created by Dockerfile
    ports:
      - "8000:80"
    networks:
      - homelab_net
  db:
    image: "mysql:8.1.0"
    container_name: "db_app"
    restart: unless-stopped
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MY_SQL_PASSWORD}
      TZ: '${GEN_TZ}'
      MY_SQL_ROOT_HOST: '%'
    volumes: 
      - "../db_homelab:/var/lib/mysql"
    networks:
      - homelab_net
  
  caddy:
    image: caddy:2.9-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/opt/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - homelab_net

volumes:
  caddy_data:
  caddy_config:

networks:
  homelab_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.18.0/24
